/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface JsfConfig {
  defaultInvalidTypeProduct?: string
  defaultRandExpMax?: number
  ignoreProperties?: string[]
  ignoreMissingRefs?: boolean
  failOnInvalidTypes?: boolean
  failOnInvalidFormat?: boolean
  alwaysFakeOptionals?: boolean
  optionalsProbability?: number
  fixedProbabilities?: boolean
  useExamplesValue?: boolean
  useDefaultValue?: boolean
  requiredOnly?: boolean
  minItems?: number
  maxItems?: number
  minLength?: number
  maxLength?: number
  refDepthMin?: number
  refDepthMax?: number
  resolveJsonPath?: boolean
  reuseProperties?: boolean
  fillProperties?: boolean
  replaceEmptyByRandomValue?: boolean
}
